### ISSUE TITLE
Allow voting w/o a comment

### ISSUE THREAD

**Issue by kimardenmiller** [Spokenvote/spokenvote#356]
- Requires a Rails Change
- Combine this task with saving first vote click, then move to optional Comment entry

**Comment by ThePletch** [comment]
Would be happy to help with this, but is this project still being actively developed?

**Comment by kimardenmiller** [comment]
Hi Steve,

Yes, still active, just a slight pause moment, soon to resume. :grin: 

I assume you are wanting to do just the Rails piece? Let me know and I'll fill you in with some more details.

/kim

**Comment by ThePletch** [comment]
I'm available to help with the Rails piece, but what else is there to be done here?

**Comment by kimardenmiller** [comment]
The “view” layer is all in Angular, but now that I think of it that part is probably all ready to go.

Assuming that’s the case, just removing the requirement of the comment with a vote should do it. Testing of course will tell us if that’s right, but seems right from what I recall.

/k

**Comment by kimardenmiller** [comment]
@ThePletch one more design consideration: The system uses comments as votes. We are removing the requirement to comment, but still need the vote. So what needs to happen is that Rails needs to a) allow a save request that's missing the comment, then b) just set the comment to a null value or something to that effect. Then Angular will need a small change to see that null value as a vote but no comment, which can be done by you or someone else, depending if you know Angular or not.

**Comment by ThePletch** [comment]
I'll be doing some travelling tonight, so I'll give it a first pass then. I don't know angular, but am entirely fine with learning enough to make this change.
