### ISSUE TITLE
Proposal: Code cleanup and refactoring

### ISSUE THREAD

**Issue by ThePletch** [Spokenvote/spokenvote#367]
While I was making my changes I noticed a few issues with the code base that I'd like the chance to resolve:
- Large sections of code are commented out instead of simply being deleted
- Some feature gating is done with direct string comparison on the URL (ApplicationController), which is split on string indices instead of something more idiomatic
- A few instances of heavily procedural code (do this, then do that) that could be refactored into something more object-oriented (ProposalsController#index, HubsController#show)

I'd love to dig through the Rails code base and clean some of this up, though I'm definitely not experienced enough to do the same for the Angular code. This shouldn't have any impact on the external features of the site or the API's format.

**Comment by kimardenmiller** [comment]
Sounds great. 

The commented out code may mean some ideas were in progress, not sure on that one. On the rest, would love to see your proposed changes. 

I’m sure you’ve noticed the Rails tests you can run to verify existing functionality. There are also a few hundred Angular tests that can be run using Karma, though that’s my strong area, so happy to pick up on that end :-)

Going to a Memorial Day BBQ, but will take a look at your code in the morning.  Thanks for the contributions!

**Comment by kimardenmiller** [comment]
Completed in PR #381 and PR #369.
